### PR TITLE
Interactive option selection

### PR DESCRIPTION
**Pull request by florimondmanca**
Hey,

I was wondering if there was a way to make choice selection more interactive, perhaps similar to what npm or vue-cli are doing. I've stumbled upon [python-inquirer](https://github.com/magmax/python-inquirer) and it does exactly this.

Hence, this PR suggests changing how CPP asks for input using Inquirer. The main benefit is an (IMO) slicker experience when selecting an option among a set of choices. An example session is shown below.

screenshot 2019-02-25 at 15 07 36

### CODE REVIEW

**Comment by florimondmanca** [comment]
Actually, I realise that [python-inquirer is not compatible with Windows](https://github.com/magmax/python-inquirer/issues/12), and some suggest [PyInquirer](https://github.com/CITGuru/PyInquirer) as a cross-platform alternative, which actually seems better maintained. I'll see how this could be done.

Also, let me know if adding a dependency is acceptable at this point.

**Comment by florimondmanca** [comment]
After some investigation, PyInquirer doesn't look as good and has some strange quirks in it. I haven't found other good-looking cross-platform alternatives, so I'm not even sure whether this is worth it anyway…

**Comment by cs01** [comment]
Oh wow python-inquirer is a really nice CLI! Thanks for putting this work in. I would definitely prefer that experience. I'd be open to adding a dependency for it, especially since CPP already has a dependency. But given its lack of windows support (thank you for noticing this now rather than after we converted the code to it) and the quirks of PyInquirer, I think a different solution that wouldn't be too hard to implement would be to modify CPP's prompt to print numerical options such as 
```
question environment:
1.) venv
2.) pipenv
3.) poetry
4.) other
> 4
enter environment:
> 
```
Then if 4 is chosen, allow the user to type freeform. Not quite as nice as using keyboard arrows, but not as bad as manually typing answers either. It wouldn't be too hard to code this up (not asking you to do it, but I wouldn't stop you if you wanted to). I would lean toward this unless a better 3rd party package is found.

**Comment by florimondmanca** [comment]
Yes, implementing a simple numbered prompt sounds good!

I’m not sure I get the need for the « Other » option, though. Isn’t that equivalent to « None » because we wouldn’t be able to generate anything for the user?

**Comment by cs01** [comment]
> I’m not sure I get the need for the « Other » option, though. Isn’t that equivalent to « None » because we wouldn’t be able to generate anything for the user?

Yeah the env was not the best example since there is a fixed set of choices. Right now none of the choices need it, but there could be a case that would. But I do agree with you; no need to add that feature for now.

**Comment by florimondmanca** [comment]
I'm closing this, will open another PR for the custom numbered question thingy. :-)

**Comment by cs01** [comment]
Oh nice, thank you! I also came across [bullet](https://github.com/Mckinsey666/bullet) which looks really nice too. 

It would be cool if something like bullet could be used first, and on windows the choice fallback could be used.

**Comment by florimondmanca** [comment]
Yep! Let's do that.

**Comment by cs01** [comment]
Oh and it looks like windows support might be coming to bullet 😄  https://github.com/Mckinsey666/bullet/issues/2#issuecomment-467487090

**Pull request closed without merging**
